Added user configuration page

diff --git a/systemInstallation/common b/systemInstallation/common
--- a/systemInstallation/common
+++ b/systemInstallation/common
@@ -1,4 +1,5 @@
 #!/bin/bash
+newroot=/mnt/new_root
 
 # Set up chroot environment
 ignore_error() {
@@ -44,6 +45,7 @@ chroot_teardown() {
     umount "${CHROOT_ACTIVE_MOUNTS[@]}"
   fi
   unset CHROOT_ACTIVE_MOUNTS
+  pacman --root $newroot -Rns $(pacman --root $newroot -Qdtq) || echo "Warning: Failed to remove unused packages"
 }
 
 chroot_add_mount_lazy() {
